Repository dadi/api, pull requests merged in 2018-04, with the labels that each got.

#400 Port changes made in 2.x to develop
  dadi/lib/controller/media.js
  dadi/lib/index.js
  dadi/lib/storage/s3.js
Labels: in progress

#399 Add new Model API
  .gitignore
  README.md
  dadi/lib/auth/tokens.js
  dadi/lib/controller/index.js
  dadi/lib/controller/media.js
  dadi/lib/fields/datetime.js
  dadi/lib/fields/index.js
  dadi/lib/fields/reference.js
  dadi/lib/fields/string.js
  dadi/lib/help.js
  dadi/lib/model/composer.js
  dadi/lib/model/count.js
  dadi/lib/model/create.js
  dadi/lib/model/createIndex.js
  dadi/lib/model/delete.js
  dadi/lib/model/find.js
  dadi/lib/model/get.js
  dadi/lib/model/getIndexes.js
  dadi/lib/model/getRevisions.js
  dadi/lib/model/getStats.js
  dadi/lib/model/history.js
  dadi/lib/model/index.js
  dadi/lib/model/update.js
  dadi/lib/model/utils.js
  dadi/lib/model/validator.js
  package.json
  scripts/coverage.svg
  test/acceptance/fields/datetime.js
  test/acceptance/fields/mixed.js
  test/acceptance/fields/object.js
  test/acceptance/fields/reference.js
  test/acceptance/rest-endpoints/collections-api/get.js
  test/acceptance/workspace/collections/v1/library/collection.book.json
  test/acceptance/workspace/collections/v1/library/collection.event.json
  test/acceptance/workspace/collections/v1/library/collection.misc.json
  test/acceptance/workspace/collections/v1/library/collection.person.json
  test/test-connector/index.js
  test/unit/controller.js
  test/unit/help.js
  test/unit/model/composer.js
  test/unit/model/index.js
  test/unit/model/utils.js
  workspace/collections/vjoin/testdb/collection.books.json
  workspace/collections/vjoin/testdb/collection.users.json
Labels: in progress, status: ready to merge

#406 Add handshake method to data connectors
  dadi/lib/datastore/index.js
  package.json
  test/unit/datastore.js
Labels: status: ready to merge

#405 Bump logger version
  package.json
Labels: type: maintenance

#411 Update README
  README.md
Labels: in progress

#413 Pass req object to hooks
  dadi/lib/controller/index.js
Labels: in progress, type: bug
